<?php

namespace RemiSan\Lock;

final class Lock
{
    /** @var string */
    private $resource;

    /** @var string */
    private $token;

    /** @var int */
    private $validityEndTime;

    /**
     * Lock constructor.
     *
     * @param string $resource The name of the resource to lock
     * @param string $token    The token generated by the Locker
     */
    public function __construct($resource, $token)
    {
        $this->resource = (string) $resource;
        $this->token = (string) $token;
        $this->validityEndTime = null;
    }

    /**
     * Get the resource name.
     *
     * @return string
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * Get the token associated with the lock.
     *
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Set the validity end time (in milliseconds since EPOCH).
     *
     * @param int $validityEndTime
     */
    public function setValidityEndTime($validityEndTime)
    {
        $this->validityEndTime = (int) $validityEndTime;
    }

    /**
     * Get the validity end time (in milliseconds since EPOCH).
     *
     * @return int
     */
    public function getValidityEndTime()
    {
        return $this->validityEndTime;
    }
}
